version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "chmod +x /app/scripts/start.sh && /app/scripts/start.sh"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.50'  # Limit CPU usage to 50%
          memory: 500M   # Limit memory to 500 MB

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'  # Limit CPU usage to 50%
          memory: 500M   # Limit memory to 500 MB