name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH Key
      run: |
        mkdir -p /tmp/.ssh                          # Create the .ssh directory
        echo "${{ secrets.AZURE_VM_PRIVATE_KEY }}" > /tmp/.ssh/id_rsa
        chmod 600 /tmp/.ssh/id_rsa                  # Ensure correct permissions for the private key

    - name: Debug SSH Connection
      run: ssh -i /tmp/.ssh/id_rsa -o StrictHostKeyChecking=no -v sa2266@srmist.edu.in@4.240.89.209 whoami

    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
        script: whoami



    
